---

- hosts: all
  become: true
  tasks:

   - name: Set authorized key in alternate location
     authorized_key:
       user: root
       path: /root/.ssh/authorized_keys
       state: absent
       key:  "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEA9fWdDRtD/crv8ox8I8dB2cPE8rRRh9GXUxNc/YuCUZm9tEMeF6LD3Mzb3PrRM0W8rF6jn3oP9HKPOhCaVIf16F3I3oqHavMJJP24bkex9Pf37kB/2O3nNfXPAnDgd92wwmxZOcTgh6+tH3lfoXxFIWbYCIUreTCEygPM5wHsOkyTTFRzc46NUED88ENZN1ifrV4WgD60j4BvD1iA63P6/BfcaBv2arFDOuPnXditRqXArUfnH1QREPZobUcK3JprPJSFGuzLURCoQtKuujDZkD8vO5DPf/AeN1G9jslQ6n8YfPFIFIq6QiQOPmEYp6qlycn/B2IlC7lru7FNybflrw== d.vacari@mivocloud.com"
